### ISSUE TITLE
Im getting the following error

### ISSUE THREAD

**Issue by cojarbi** [egradman/rhinotools#1]
<img width="418" alt="screen shot 2016-07-09 at 6 32 23 pm" src="https://cloud.githubusercontent.com/assets/16444438/16710831/8c5f638e-4603-11e6-8659-2e871399e1da.png">

**Comment by egradman** [comment]
so sorry.  `finger.py` contains functions that other scripts rely upon.  `fingerjoint/xyz.py` is what I called `finger3` in the video, and `fingerjoint/two.py` is what I called `finger2`.

I have aliases set up to run these.

I'll add documentation shortly!
